all-features = false
no-default-features = false

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    "RUSTSEC-2023-0018",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
  { name = "ring", allow = ["OpenSSL"] },
]
unused-allowed-license = "allow"

[[licenses.clarify]]
name = "ring"
expression = "OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "allow"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
